# Generated by Django 5.0.7 on 2024-07-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='data',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
