# Generated by Django 5.0.7 on 2024-07-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='data',
        ),
    ]
